### ISSUE TITLE
Respect message specific VisibilityTimeout

### ISSUE THREAD

**Issue by moyuanhuang** [ruby-shoryuken/shoryuken#591]
Happy new year!

According to [AWS documenation][doc], it's possible to set the `VisibilityTimeout` for a specific message regardless of the `VisibilityTimeout` value in the queue level. This is useful since in our application, messages in one queue can be processed by different shoyuken workers, which takes up very different amount of time. We want to set the visibility timout to a bigger value for those messages that takes longer time, so that it won't get processed multiple times.

Fortunately, we were able to use the `Message#visibility_timeout=` setter to change the message's visibility timeout (from 60 seconds to 2 hours in this case). However, shoryuken would log warnings like this

```
started at 2020-01-04 08:01:09 +0000
...
exceeded the queue visibility timeout by 705623.076762 ms
completed in: 765623.076762 ms
```

...which is misleading.

I think this is caused by shoryuken always uses the queue level visibility timeout, and not respecting the visibility timeout in the message level

https://github.com/phstc/shoryuken/blob/af6ba758767aa7e541cae0ad3e4b146ef8eb7792/lib/shoryuken/middleware/server/timing.rb#L16

I'm happy to open a PR if this is a legit issue or otherwise I might be missing something here?

Thanks!

[doc]: https://docs.aws.amazon.com/AWSSimpleQueueService/latest/APIReference/API_ChangeMessageVisibility.html

**Comment by phstc** [comment]
Hi @moyuanhuang 

Happy new year!

I will be happy to review a PR changing that code to verify the `sqs_msg` visibility timeout if any otherwise fallback to the queue visibility timeout for a less misleading message. I don't remember if the `sqs_msg` returns the queue visibility timeout if not set at the message level you may need a fallback to the queue one, but it is worth checking before adding the fallback. 

BTW there's this option [`auto_visibility_timeout`](https://github.com/phstc/shoryuken/wiki/Worker-options#auto_visibility_timeout) that could help your use case as well.
