### ISSUE TITLE
warning: instance variable @logger not initialized

### ISSUE THREAD

**Issue by ioquatix** [ruby-shoryuken/shoryuken#616]
This message is printed when running with warnings.

```
shoryuken-5.0.4/lib/shoryuken/logging.rb:33: warning: instance variable @logger not initialized
```

https://github.com/phstc/shoryuken/blob/7ce3e7540375798866d3bde482f3869bb6eee6df/lib/shoryuken/logging.rb#L33

:pushpin: #617

**Comment by ioquatix** [comment]
I would suggest to reproduce this and other similar issues to run your tests with warnings.

Try `RUBYOPT=-w rspec` or whatever your test framework is.

Let me know if that doesn't help.

**Comment by phstc** [comment]
@ioquatix thank you, that worked! 

PR reopened and merged https://github.com/ruby-shoryuken/shoryuken/pull/701

**Comment by ioquatix** [comment]
Thanks.

After making that change, do you still get warnings?

**Comment by phstc** [comment]
The warning you listed in the issue is gone! 

I'm getting active_support ones.

> ruby/2.7.0/lib/ruby/gems/2.7.0/gems/activesupport-4.2.11.3/lib/active_support/core_ext/hash/keys.rb:8: warning: method redefined; discarding old transform_keys
> ruby/2.7.0/lib/ruby/gems/2.7.0/gems/activesupport-4.2.11.3/lib/active_support/core_ext/hash/keys.rb:19: warning: method redefined; discarding old transform_keys!
> ruby/2.7.0/lib/ruby/gems/2.7.0/gems/activesupport-4.2.11.3/lib/active_support/core_ext/hash/slice.rb:21: warning: method redefined; discarding old slice

**Comment by ioquatix** [comment]
I'm surprised because `@logger || ...` if `@logger` is undefined should create a warning. Do you test this case?

**Comment by phstc** [comment]
Hi @ioquatix thank you for double checking!

I tested as you suggested `RUBYOPT=-w be rspec spec/shoryuken/client_spec.rb`  (can be any other spec, `client_spec.rb` was randomly chosen).

Without the change, I got the same warning you reported, with the change that warning was gone.

The difference is `||=` instead of `||`.

Can you please check it out [here](https://github.com/ruby-shoryuken/shoryuken/blob/f679f9492098be402c76749a79d2764c845a8f7f/lib/shoryuken/logging.rb#L33)? A second pair of eyes is welcome!
