### ISSUE TITLE
USR1 and TSTP cause the auto visibility timeout refresh to stop running

### ISSUE THREAD

**Issue by erozycki** [ruby-shoryuken/shoryuken#636]
### The problem

Upon receiving USR1 or TSTP, Shoryuken executes `@launcher.stop`, which executes `Concurrent.global_io_executor.shutdown`: https://github.com/phstc/shoryuken/blob/bc7938942270a1171d1597064698d88c3f36a4ec/lib/shoryuken/launcher.rb#L26-L39
However, the AutoExtendVisibility middleware uses an instance of Concurrent::TimerTask, which runs in Concurrent's global threadpool (and unfortunately, there is no option to specify the thread pool used by an instance of TimerTask): https://github.com/phstc/shoryuken/blob/bc7938942270a1171d1597064698d88c3f36a4ec/lib/shoryuken/middleware/server/auto_extend_visibility.rb#L28-L41
So when USR1 or TSTP is received, the `Concurrent.global_io_executor` is shut down, and therefore all Concurrent::TimerTask instances are immediately stopped. So AutoExtendVisibility stops running, even though jobs may still be executing.  

This causes significant issues with my setup:
1. I use a visibility timeout of 5m, with AutoExtendVisibility enabled
2. Some of my jobs are long-running (unfortunately, some can run for over an hour)
3. I send my Shoryuken processes USR1 when I deploy, to do a rolling restart. I deploy frequently, often multiple times per day.
4. Recently, I have begun sending USR1 to a Shoryuken process when its memory usage exceeds 800 MB, so that it will exit after it finishes. (I performs these restarts to mitigate Ruby's memory bloat/retention issues.)
5. Due to 3 and 4, my Shoryuken processes often receive USR1 while they are working on long-running jobs. AutoExtendVisibility stops running and the visibility timeout expires for the jobs' messages, so the jobs are reprocessed - potentially reprocessed many times in the case of long-running jobs that use a lot of memory.

### Potential solutions

1. If I set `Shoryuken.launcher_executor` to a non-global threadpool, then `@launcher.stop` will shut down this non-global threadpool, instead of the `Concurrent.global_io_executor` threadpool. Would this cause any issues? Shoryuken.launcher_executor isn't documented anywhere, but it seems like it should be safe for me to set Shoryuken.launcher_executor. It also could make sense for Shoryuken to use a non-global threadpool by default.
2. I could create an alternate implementation of AutoExtendVisibility that does not rely on Concurrent.global_io_executor. I already have an alternate implementation of AutoExtendVisibility that I'm testing. But approach 1 seems better.
3. Any other/better solutions?

Note that solutions 1 and 2 would make it so that `@launcher.stop` does not clean up the AutoExtendVisibility threads - but I think this is okay, because AutoExtendVisibility has `ensure ... timer.kill if timer ... end` after the `yield`.

P.S. Thanks for working on Shoryuken @phstc, it's great and I love it.

**Comment by erozycki** [comment]
It's not clear to me that solution 1 is safe. `@launcher.executor` isn't used everywhere. In some places there is e.g. `Concurrent::Future.execute { ... }`, which defaults to using Concurrent.global_io_executor. So if I set `Shoryuken.launcher_executor`, then `Concurrent::Future.execute { ... }` won't get canceled when `@launcher.stop` is called.

**Comment by nc-holodakg** [comment]
@erozycki did you have any luck finding a solution?

**Comment by erozycki** [comment]
@nc-holodakg i ended up doing this:

```
Shoryuken.configure_server do |config|
  config.server_middleware do |chain|
    chain.remove(Shoryuken::Middleware::Server::AutoExtendVisibility)
    chain.add(AutoExtendVisibilityV2)
  end
end
```

where `AutoExtendVisibilityV2` is defined as follows (note that this implementation is a bit rough around the edges, in particular I should be using a thread pool instead of `Thread.new do ... end`):

```
class AutoExtendVisibilityV2
  include Shoryuken::Util

  EXTEND_UPFRONT_SECONDS = 7

  def call(worker, queue, sqs_msg, body)
    return yield unless worker.class.auto_visibility_timeout?

    if sqs_msg.is_a?(Array)
      logger.warn { "Auto extend visibility isn't supported for batch workers" }
      return yield
    end

    timer = auto_visibility_timer(worker, queue, sqs_msg, body)
    yield
  ensure
    timer.kill if timer
  end

  private

  class MessageVisibilityExtender
    include Shoryuken::Util

    def initialize
      @killed = Concurrent::AtomicBoolean.new(false)
    end

    def kill
      @killed.make_true
    end

    def auto_extend(_worker, queue, sqs_msg, _body)
      queue_visibility_timeout = Shoryuken::Client.queues(queue).visibility_timeout
      refresh_interval = queue_visibility_timeout - EXTEND_UPFRONT_SECONDS

      Thread.new do
        loop do
          next_refresh_at = Time.current + refresh_interval
          while Time.current < next_refresh_at
            sleep(1)
            break if @killed.true?
          end
          break if @killed.true?

          logger.debug do
            "Extending message #{queue}/#{sqs_msg.message_id} visibility timeout by #{queue_visibility_timeout}s"
          end

          sqs_msg.change_visibility(visibility_timeout: queue_visibility_timeout)
        rescue => ex
          logger.error do
            "Could not auto extend the message #{queue}/#{sqs_msg.message_id} visibility timeout. Error: #{ex.message}"
          end
        end
      end
    end
  end

  def auto_visibility_timer(worker, queue, sqs_msg, body)
    MessageVisibilityExtender.new.tap { |extender| extender.auto_extend(worker, queue, sqs_msg, body) }
  end
end
```

**Comment by cjlarose** [comment]
Hey @erozycki! I've recently been added as a maintainer to shoryuken and I'm glad you were able to find a workaround, but I think what you experienced is definitely not desirable. Of course, relying on auto-visibility timeout altogether isn't recommended--jobs should still be idempotent, but it'd be great if the default AutoVisibilty implementation at least did its best to make sure to continue running for as long as the job still up.

I'll experience with this over the next week and see what we can do.

**Comment by erozycki** [comment]
Hey @cjlarose, that's great to hear! Thanks for planning on looking into it.

Also, I agree that one should create idempotent jobs and not rely on the auto visibility timeout extension - however #636 is a significant issue even for idempotent jobs. First, it's very inefficient for a job to get executed many times. Second, if a job is dequeued too many times then it will get sent to the dead-letter queue.

**Comment by cjlarose** [comment]
I opened #660 in order to get integration tests back up and running correctly. My thought was that it'll help us reproduce this issue and write a regression test for it. In doing so, I found that the tests relied on setting `Shoryuken.launcher_executor` explicitly. If the tests use the default `global_io_executor`, they seem to get stuck.

I also found #456 which indicates that `Shoryuken.launcher_executor` is definitely public API, even though it's not documented anywhere.

Still looking into the auto visibility timeout issue.

**Comment by cjlarose** [comment]
I don't know what the best solution is going to be yet, but figured I could respond with some of what the original issue described

> If I set `Shoryuken.launcher_executor` to a non-global threadpool, then `@launcher.stop` will shut down this non-global threadpool, instead of the `Concurrent.global_io_executor` threadpool. Would this cause any issues? Shoryuken.launcher_executor isn't documented anywhere, but it seems like it should be safe for me to set Shoryuken.launcher_executor. It also could make sense for Shoryuken to use a non-global threadpool by default.



It seems safe to me to set a different thread pool for `Shoryuken.launcher_executor`. The option was added specifically to allow users to override it (#456). That's at least a nice workaround for now. Using a non-global `CachedThreadPool` seems to be the least disruptive change (`Concurrent.global_io_executor` is itself a `CachedThreadPool`)

```ruby
Shoryuken.launcher_executor = Concurrent::CachedThreadPool.new auto_terminate: true
```

> It's not clear to me that solution 1 is safe. `@launcher.executor` isn't used everywhere where a thread pool is used. In some places there is e.g. `Concurrent::Future.execute { ... }`, which defaults to using Concurrent.global_io_executor. So if I set `Shoryuken.launcher_executor`, then `Concurrent::Future.execute { ... }` will still be running in `Concurrent.global_io_executor` and therefore won't get canceled when `@launcher.stop` is called.

The only place I can find that uses `Concurrent::Future.execute { ... }` is [`Shoryuken::Launcher#start_managers`](https://github.com/cjlarose/shoryuken/blob/0f97f5bcb1f7eadcafb2441a093ff9e103808c1a/lib/shoryuken/launcher.rb#L41-L46).  It's true that this code (perhaps not deliberately) implicitly places a task onto the `Concurrent.global_io_executor`. However, this is extraordinarily short-lived and only happens when a `Shoryuken::Lancher` first starts up. The task enqueued to the `global_io_executor` is just to `post` a `Manager`'s `dispatch` operation onto the `Shoryuken.launcher_executor`. All actual dispatching (and worker code invocation) happens on `Shoryuken.launcher_executor`.

That said, it's still technically possible to call `Shoryuken::Launcher#stop` shortly after startup, and cause a `shutdown` of the `Shoryuken.launcher_executor` before the work in `global_io_executor` has completed. I think that's okay though since the tasks will just fail when they try to `post` to `Shoryuken.launcher_executor`, and we wouldn't actually want that work to complete anyway.

> * I could create an alternate implementation of AutoExtendVisibility that does not rely on Concurrent.global_io_executor. I already have an alternate implementation of AutoExtendVisibility that I'm testing. But approach 1 seems better.

I think this might be the right approach. There doesn't seem to be a good reason why `Concurrent::TimerTask` doesn't let us specify a different `executor` on which to actually execute the tasks. If we change `AutoExtendVisibility`'s `Concurrent::TimerTask`s to execute on a separate thread pool from `Shoryuken.launcher_executor`, that seems like it would solve the problem (the `TimerTask`s could keep doing their thing even after `Shoryuken.launcher_executor#shutdown` is executed).

The downside to changing `concurrent-ruby` of course is that (short of monkey-patching or distributing a modified `TimerTask` within shoryuken's source), we'd have to get a PR accepted and merged, then require the newer version in Shoryuken's `gemspec`, forcing users to upgrade.

Your `AutoExtendVisibilityV2` is, as you said, "rough around the edges", but it's kinda nice since it doesn't force users to upgrade a dependency. It basically just re-implements the functionality of `TimerTask` without doing any work on the `global_io_executor` or on `Shoryuken::launcher_executor`. You mentioned that it doesn't use a thread pool, but it should be possible to do something very similar, but just by dispatching work to a separate `Concurrent::CachedThreadPool`.

**Comment by cjlarose** [comment]
I missed one thing that's kinda important

> It also could make sense for Shoryuken to use a non-global threadpool by default.

Since `Shoryuken.launcher_executor` is configurable, it's reasonable that users set this explicitly to `Concurrent.global_io_executor`. So while we could use a non-global threadpool for `Shoryuken.launcher_executor` by default, an ideal solution to this problem would work even if `Shoryuken.launcher_executor` is `Concurrent.global_io_executor`.
