### ISSUE TITLE
Compatible with Ruby 2.2.3?

### ISSUE THREAD

**Issue by tai-acall** [ruby-shoryuken/shoryuken#653]
Hello there,
I'm considering switching from the Sidekiq + Redis solution to the Shoryuken + AWS SQS.
Is it possible apply the shoryuken to Ruby 2.2.3 with older version?

if not, any others AWS SQS compatible solution will be helpful.

**Comment by cjlarose** [comment]
Shoryuken is [officially only compatible with Ruby 2.4 and later](https://github.com/ruby-shoryuken/shoryuken/blob/76a5a6c887d824b83b627f69a831c5b9bee4ea97/README.md#requirements). Ruby 2.2 has been [EOL'ed from the Ruby team since 2018](https://www.ruby-lang.org/en/downloads/branches/).

If you have an application that depends on Ruby 2.2.3, I strongly recommend upgrading your Ruby version.
