### ISSUE TITLE
Shoryuken - No worker found error.  

### ISSUE THREAD

**Issue by svogt0511** [ruby-shoryuken/shoryuken#655]
Seems similar to issue #452 .  I get these errors in the log:

2021-02-16T22:01:32Z 226 TID-od968 ERROR: No worker found for development_usage
2021-02-16T22:02:03Z 226 TID-odb98 ERROR: No worker found for development_usage
2021-02-16T22:02:03Z 226 TID-odb98 ERROR: No worker found for development_usage
...

Rails 5.2.4.1, Ruby 2.4.4, Shoryuken 3.3.1, ActiveJob, AWS SQS.  Jobs are located in app/jobs.

`bundle exec shoryuken -R -C config/shoryuken.yml`

I am using `queue_as` in job files.  

I use `config.active_job.queue_name_prefix = Rails.env` in config/application.rb and `Shoryuken.active_job_queue_name_prefixing = true` in config/initializers/_shoryuken.rb.

Interesting to note that I have 2 queues, and I only get the log file errors for the development_usage queue.

Also interesting to note that it seems to work.  I would just like to stop the log file messages as I seem to get a number of them every 20-30 seconds.

Any help you can give me is appreciated.  Thanks.

**Comment by cjlarose** [comment]
The message `No worker found for #{queue_name}` message is logged any time a message appears on the queue and shoryuken can't determine which worker to assign the message to. The relevant code is in `DefaultWorkerRegistry#fetch_worker`

https://github.com/ruby-shoryuken/shoryuken/blob/4ee01c74207cfa91ac6ceb49c55ffbe17de56926/lib/shoryuken/default_worker_registry.rb#L16-L27

When a message is enqueued, shoryuken writes the worker class name into the SQS message attribute `shoryuken_class`.

The most common cause of that message being written to the log is that the worker class has been renamed or deleted since it was enqueued. I think you might be seeing the same message every 20-30 seconds because you have some old messages in your queue that have a bad `shoryuken_class` attribute. They fail every time, then reappear after the queue's configured visibility timeout.

**Comment by cjlarose** [comment]
Closing for now. Lemme know if the above didn't end p being the problem.
