### ISSUE TITLE
Lost shoryuken_class in DLQ

### ISSUE THREAD

**Issue by mkarganov** [ruby-shoryuken/shoryuken#659]
Hi, for some reason during moving failed jobs from DQL to normal queue jobs are consumed by wrong shoryuken worker. 

I checked the [code](https://github.com/ruby-shoryuken/shoryuken/blob/master/lib/shoryuken/default_worker_registry.rb#L15) and see that it expects some `shoryuken_class` in message attributes. But if I check messages in DLQ - there are just plain attributes without any `shoryuken's` attributes.

I am using several workers connected to `default_background_queue`.

What could be the reason?

**Comment by cjlarose** [comment]
Are you using Shoryuken to consume messages directly from the dead-letter queue? Or did you write some code that pulls messages from the dead-letter queue and then push them back into the normal queue?

If it's the latter, it's quite easy to pull the messages from the queue in a way that doesn't capture the MessageAttributes. 

IIRC, `attribute_names` must be specified when using `receive_message`, otherwise the MessageAttributes will appear to be empty when you pull the messages from the queue

https://docs.aws.amazon.com/sdk-for-ruby/v3/api/Aws/SQS/Client.html#receive_message-instance_method

**Comment by mkarganov** [comment]
Thank you for your response. Yes, I am using custom code of `Aws::SQS::QueuePoller.new().poll()` I see that `attribute_names` can also be passed in a constructor there. Should I pass 'All' there or some specific attributes?

**Comment by cjlarose** [comment]
`All` should be fine. `shoryuken` itself specifies `All` when it receives messages https://github.com/cjlarose/shoryuken/blob/90b66f99385c1a063dbd7a5b987e1e300bdc2aaa/lib/shoryuken/fetcher.rb#L53

**Comment by mkarganov** [comment]
Thank you! it is solved 👍🏻 . Event 'All' was not needed, `message_attributes` were just not passed through
