### ISSUE TITLE
Shoryuken worker is keep retrying with last retry interval for infinite times after getting failure

### ISSUE THREAD

**Issue by Ramyani-QI** [ruby-shoryuken/shoryuken#669]
Hi, I was using `shoryuken_options retry_intervals: [120, 240] ` as per the wiki https://github.com/ruby-shoryuken/shoryuken/wiki/Worker-options#retry_intervals But noticed that after getting failure, first and second retry attempts were as expected but after second retry also that message was keep retrying after every 240 seconds (i.e. same as last retry interval).

While debugging found this piece of code was the probable cause of this issue.
https://github.com/ruby-shoryuken/shoryuken/blob/master/lib/shoryuken/middleware/server/exponential_backoff_retry.rb#L33-L59

![image](https://user-images.githubusercontent.com/67254790/123814606-7118f880-d913-11eb-8fe5-5bd20c0983aa.png)

Whenever it is exceeding the receive count it was setting the next visibility timeout based on last retry intervals and that is why its becoming a infinite retry sequence.

Is there any way to get rid from this other than overriding these library methods in application end?

**Comment by cjlarose** [comment]
This is admittedly a little confusing, but the list of `retry_intervals` doesn't determine the maximum receive count. When a message because visible on a queue, that's basically outside of the control of Shoryuken.

If you'd like to make it so that messages are removed from the queue automatically after a given number of receives, the easiest way to accomplish that is to specify a _redrive policy_ with a dead-letter queue. Specifiying a redrive policy for the queue is outside of the scope of shoryuken, but the relevant SQS docs are handy: https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-dead-letter-queues.html#sqs-dead-letter-queues-how-they-work

If you set a redrive policy with a `maxReceiveCount` of, say 10, then whenever the message is received 10 times and isn't deleted, SQS will remove the message from the queue and push it into a dead-letter queue. That dead-letter queue is useful for inspecting which messages failed for debugging purposes.
