### ISSUE TITLE
configuring a custom polling_strategy 

### ISSUE THREAD

**Issue by awr** [ruby-shoryuken/shoryuken#675]
In the docs it's clear that you can extend the polling strategies with a custom strategy (which is fantastic), but it's not clear how to configure use of them -- in particular when using a config file.

For example, when I use a config such as 
```yaml
delay: 0
concurrency: 25
polling_strategy: WorkerPolling
queues:
  - dev-notifications
```

And start with `bundle exec shoryuken -C test-shoryuken.yaml -r ./app.rb` then I run into an exception

```
bundler: failed to load command: shoryuken (/code/vendor/bundle/ruby/3.0.0/bin/shoryuken)
/code/vendor/bundle/ruby/3.0.0/gems/shoryuken-5.2.2/lib/shoryuken/options.rb:68:in `polling_strategy': WorkerPolling is not a valid polling_strategy (ArgumentError)
	from ~/.rbenv/versions/3.0.2/lib/ruby/3.0.0/forwardable.rb:238:in `polling_strategy'
	from /code/vendor/bundle/ruby/3.0.0/gems/shoryuken-5.2.2/lib/shoryuken/launcher.rb:75:in `block in create_managers'
	from /code/vendor/bundle/ruby/3.0.0/gems/shoryuken-5.2.2/lib/shoryuken/launcher.rb:72:in `each'
	from /code/vendor/bundle/ruby/3.0.0/gems/shoryuken-5.2.2/lib/shoryuken/launcher.rb:72:in `map'
	from /code/vendor/bundle/ruby/3.0.0/gems/shoryuken-5.2.2/lib/shoryuken/launcher.rb:72:in `create_managers'
	from /code/vendor/bundle/ruby/3.0.0/gems/shoryuken-5.2.2/lib/shoryuken/launcher.rb:6:in `initialize'
	from /code/vendor/bundle/ruby/3.0.0/gems/shoryuken-5.2.2/lib/shoryuken/runner.rb:43:in `new'
	from /code/vendor/bundle/ruby/3.0.0/gems/shoryuken-5.2.2/lib/shoryuken/runner.rb:43:in `run'
	from /code/vendor/bundle/ruby/3.0.0/gems/shoryuken-5.2.2/bin/shoryuken:42:in `start'
	from /code/vendor/bundle/ruby/3.0.0/gems/thor-1.1.0/lib/thor/command.rb:27:in `run'
	from /code/vendor/bundle/ruby/3.0.0/gems/thor-1.1.0/lib/thor/invocation.rb:127:in `invoke_command'
	from /code/vendor/bundle/ruby/3.0.0/gems/thor-1.1.0/lib/thor.rb:392:in `dispatch'
	from /code/vendor/bundle/ruby/3.0.0/gems/thor-1.1.0/lib/thor/base.rb:485:in `start'
	from /code/vendor/bundle/ruby/3.0.0/gems/shoryuken-5.2.2/bin/shoryuken:53:in `<top (required)>'
	from /code/vendor/bundle/ruby/3.0.0/bin/shoryuken:23:in `load'
	from /code/vendor/bundle/ruby/3.0.0/bin/shoryuken:23:in `<top (required)>'
...
```

This makes sense, given https://github.com/ruby-shoryuken/shoryuken/blob/master/lib/shoryuken/options.rb#L59 but I'm not sure what the expectation is for passing in a `Class` from the config file. Alternatively, how should I be calling this?

Any help would be much appreciated :)

**Comment by cjlarose** [comment]
This actually looks like a bug. Well, really, there are two bugs:

1. It's not actually possible to specify a custom `polling_strategy` when defining groups using the YAML configuration syntax and
2. If you decide to use the Ruby configuration API (i.e., `Shoryuken.configure_server`), there's no option in the `add_group` method to specify the polling strategy.

Thanks for finding this holes. I'm open to pull requests to fix either of these issues.

**Comment by cjlarose** [comment]
Also @awr, I'm curious what your custom polling strategy does and what your use case is since maybe there's a gap in Shoryuken's available offerings.

**Comment by awr** [comment]
I'm trying out a policy that allows me to have *runtime* enabling/disabling of workers (state managed via some store -- redis in our case). The goal is to ensure that they don't have any impact on sqs, including attempt count to avoid redrive policies kicking in.

This would enable devs to enable/disable workers without having to have infra level access. If this works, it'll ultimately be exposed through some UI that affects the state of the store.

If there's a better way to achieve this, I'm all ears :)

I'll try my hand at a PR (likely option 1 above).

**Comment by cjlarose** [comment]
> I'm trying out a policy that allows me to have _runtime_ enabling/disabling of workers (state managed via some store -- redis in our case). The goal is to ensure that they don't have any impact on sqs, including attempt count to avoid redrive policies kicking in.
> 
> This would enable devs to enable/disable workers without having to have infra level access. If this works, it'll ultimately be exposed through some UI that affects the state of the store.

That sounds really cool! I could see something like this also being useful in a production environment, too, where you'd want the ability to enable/disable consumption of messages from particular queues at runtime (such as during some sort of production incident).

There are a lot of different ways to approach this problem, but I think your approach of hijacking the polling strategy might be the easiest to implement. I hesitate to do something like that myself because I think ideally I'd want to configure the polling strategy independent of the mechanism for deciding which queues are on or off.

I think my own preference would be to make it so that when Shoryuken is initialized (assuming you're using `Shoryuken.configure_server`), it just doesn't add any queues that are marked as "disabled" in Redis. Then you can start up a separate thread that listens to Redis pub/sub events. If an event comes through indicating that the queue settings have changed, then you can just trigger Shoryuken to terminate. Assuming it's running under a process manager, it'll be restarted with the new configuration.

> I'll try my hand at a PR (likely option 1 above).

I look forward to it!
