### ISSUE TITLE
Pushing message to SQS without active job. 

### ISSUE THREAD

**Issue by GiriCredAvenue** [ruby-shoryuken/shoryuken#688]
1) I have a use case where a particular job needs to be executed at every day at 2 am UTC, so we created Amazon cloud watch rule, which will push the given message to the sqs queue.  
2) My message is in the same format as pushed by the active job. `{ "job_class": "ActivityJob", "arguments": [], "locale": "en" }`
3) during this i am receiving a error `No worker found for ActivityJob`. 
4) while debugging i found, @workers instance variable in `DefaultWorkerRegistry` class is lazily loaded, so workers instance variable will be empty and `Shoryuken.worker_registry.fetch_worker` returns a empty value.   

I didn't go through the entire code just have a skim, i may be wrong. kindly help in finding the root cause, if the above observation are wrong.

Stack trace.
![image](https://user-images.githubusercontent.com/84510206/143668008-8d47377e-061c-4872-a611-369ac253d678.png)

**Comment by cjlarose** [comment]
The most common cause of `No worker found for _` errors is a missing SQS Message Attribute.

Shoryuken expects all messages to include an SQS Message Attribute with the key `shoryuken_class` and whose value corresponds to the name of the Shoryuken worker. If you're using ActiveJob, the name of the Shoryuken worker is always `ActiveJob::QueueAdapters::ShoryukenAdapter::JobWrapper`.

The relevant code for how Shoryuken enqueues an ActiveJob messages to SQS is here: https://github.com/ruby-shoryuken/shoryuken/blob/af0c90c655b81e4c38c47ab8c76bea9d16cc543e/lib/shoryuken/extensions/active_job_adapter.rb#L33-L42

**Comment by GiriCredAvenue** [comment]
@cjlarose I am using AWS cloud watch rules to push a event at scheduled time by specifying SQS as a target in that there is no option to set a header, so can we set the key in body?

**Comment by cjlarose** [comment]
Shoryuken does not offer an easy way to specify the `shoryuken_class` in the message body. Since you're unable to specify the `shoryuken_class` in the SQS message attributes, my recommendation to you is to use a custom `worker_registry`. For example, you can subclass the [`DefaultWorkerRegistry`](https://github.com/ruby-shoryuken/shoryuken/blob/af0c90c655b81e4c38c47ab8c76bea9d16cc543e/lib/shoryuken/default_worker_registry.rb).

```ruby
class MyCustomRegistry < Shoryuken::DefaultWorkerRegistry
  def fetch_worker
    worker_class = !message.is_a?(Array) &&
                   message.message_attributes &&
                   message.message_attributes['shoryuken_class'] &&
                   message.message_attributes['shoryuken_class'][:string_value]

    worker_class = begin
                     worker_class.constantize
                   rescue
                     ActiveJob::QueueAdapters::ShoryukenAdapter::JobWrapper
                   end

    worker_class.new if worker_class
  end
end

Shoryuken.worker_registry = MyCustomRegistry.new
```

**Comment by GiriCredAvenue** [comment]
@cjlarose In the DefaultWorkerRegistry in rescue block code return `@workers[queue]`, which means if that `@workers` instance variable is loaded already by some other job(which is pushed via active job) then it will work right?

in my case multiple job are pushed in the same SQS queue like  `ActivityJob`, `MailJob` both have `queue_as` same queue name.

**Comment by GiriCredAvenue** [comment]
@cjlarose one more doubt, in the `processor` class, `worker` method, we call `Shoryuken.worker_registry` it seems this will always return `DefaultWorkerRegistry` not a custom registry we defiened. can you correct me if i am wrong? 


![image](https://user-images.githubusercontent.com/84510206/143727644-e6f33ddb-ad6e-4310-8ef2-24132500911c.png)
![image](https://user-images.githubusercontent.com/84510206/143727685-ed995e5c-2e42-45be-a002-0c08a0a8c929.png)

**Comment by cjlarose** [comment]
> my question is if `ActivityJob` task is enqueued before `MailJob` then `@workers` instance variable is loaded with the queue name and corresponding JobWrapper right? so that now due to rescue block `MailJob` task will be executed even though there is `shoryuken_class` attribute in the SQS message.

Relying on `@workers[queue]` is indeed not reliable (especially when using multiple workers on the same queue) because it depends on load order. I don't recommend you rely on this behavior which is why I don't reference `@workers[queue]` in my suggested implementation of `MyCustomRegistry`.

For context, Shoryuken didn't always have the ability to put messages for different workers into the same queue. That's why `@workers[queue]` was used to determine which worker class to use. Later, the feature was added to allow multiple workers on the same queue, but it became necessary to specify the exact worker using the `shoryuken_class` SQS message attribute. For backwards compatibility, we fallback to `@workers[queue]` only if the `shoryuken_class` was not specified.



> all the queues going to have only same class name (ActiveJob::QueueAdapters::ShoryukenAdapter::JobWrapper) as value. this way we can avoid sending `shoyuken_class` key in every message (which i feel redundant and overhead).
> 
> I find sending a key `shoyuken_class` where it's value is not going to change, a bit odd.

If you're _only_ using ActiveJob to define your worker classes, then you're right that all of your SQS messages will have the `shoryuken_class` attribute set to `ActiveJob::QueueAdapters::ShoryukenAdapter::JobWrapper`. The reason why the `shoryuken_class` attribute is important is if you define workers using the shoryuken native interface (subclassing `Shoryuken::Worker` directly (see https://github.com/ruby-shoryuken/shoryuken/wiki/Getting-Started for an example)

> @cjlarose one more doubt, in the `processor` class, `worker` method, we call `Shoryuken.worker_registry` it seems this will always return `DefaultWorkerRegistry` not a custom registry we defiened. can you correct me if i am wrong?

The module body of `Shoryuken::Options` is evaluated early in the application initialization process. If you override `Shoryuken.worker_register = MyCustomRegistry` in a Rails initializer, for example, the value will be successfully overridden. I'm confident this mechanism works because I use a custom registry in my own applications.

**Comment by GiriCredAvenue** [comment]
@cjlarose Thank you so much CustomRegistry solution worked for me.

**Comment by GiriCredAvenue** [comment]
@cjlarose One more doubt, is there any way we can monitor the shoryuken is alive(polling stopped or not), we are trying to sent this to some observability service like newrelic, so that if polling stops, we can set an alert and restart the servers?

**Comment by cjlarose** [comment]
@GiriCredAvenue For monitoring recommendations, I think this issue might help: #674
